services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - reverse-proxy
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5050:5050"
    depends_on:
      - reverse-proxy
    volumes:
      - ./server:/server
      - /server/node_modules

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
