services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app.prod
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`mern-front.johanna-stoicanescu.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server.prod
    ports:
      - "5050:5050"
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`mern-back.johanna-stoicanescu.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    external: true
