
FROM node:14-alpine as build

WORKDIR /server

COPY server/package*.json .

RUN npm install --production

COPY ./server .

FROM node:14-alpine

WORKDIR /server

COPY --from=build /server/dist .

EXPOSE 5050

CMD ["node", "server.js"]