FROM node:14-alpine as build

WORKDIR /app

COPY app/package*.json .

RUN npm install --production

COPY ./app .

RUN npm run build

FROM node:14-alpine

WORKDIR /app

COPY --from=build /app/dist .

EXPOSE 3000

CMD ["npm", "start"]